sonar.projectKey=ValeriaSpektor_sonarqube-js-quality-demo
sonar.organization=valeriaspektor

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
